import type { AssessmentResponse } from "@shared/routes";

const formatNumberValue = (value: unknown, suffix = ""): string => {
  if (value === undefined || value === null || value === "") {
    return "N/A";
  }
  const numberValue = Number(value);
  if (!Number.isFinite(numberValue)) {
    return String(value);
  }
  return `${numberValue}${suffix}`;
};

export function formatAssessmentSummary(assessment: AssessmentResponse): string {
  const category = assessment.riskCategory || "Unknown";
  const score = assessment.riskScore !== undefined && assessment.riskScore !== null
    ? `${Number(assessment.riskScore).toFixed(1)}%`
    : "N/A";
  const age = assessment.age !== undefined && assessment.age !== null
    ? String(assessment.age)
    : "N/A";
  const gender = assessment.gender || "Unknown";
  const bmi = assessment.bmi !== undefined && assessment.bmi !== null
    ? Number(assessment.bmi).toFixed(1)
    : "N/A";
  const hba1c = assessment.hba1cLevel !== undefined && assessment.hba1cLevel !== null
    ? `${Number(assessment.hba1cLevel).toFixed(1)}%`
    : "N/A";
  const bloodGlucose = assessment.bloodGlucoseLevel !== undefined && assessment.bloodGlucoseLevel !== null
    ? `${Number(assessment.bloodGlucoseLevel).toFixed(0)} mg/dL`
    : "N/A";

  const clinicianAdvice = assessment.prediction?.clinicianAdvice ?? [];
  const patientAdvice = assessment.prediction?.patientAdvice ?? [];
  const explanation = assessment.explanation?.summary ?? "";
  const attentionPriorities = assessment.attentionNavigator?.priorities ?? [];
  const recommendations = assessment.recommendations ?? [];

  return [
    "Risk Assessment Summary",
    "",
    `Patient: ${assessment.patientName || "Unknown"}`,
    `Age: ${age}`,
    `Gender: ${gender}`,
    "",
    `Risk Category: ${category}`,
    `Risk Score: ${score}`,
    "",
    `BMI: ${bmi}`,
    `HbA1c: ${hba1c}`,
    `Blood Glucose: ${bloodGlucose}`,
    "",
    "Model explanation:",
    explanation || "No summary explanation was available.",
    "",
    "Clinician follow-up notes:",
    ...clinicianAdvice.map((item) => `- ${item}`),
    "",
    "Patient guidance:",
    ...patientAdvice.map((item) => `- ${item}`),
    "",
    "Recommendations:",
    ...recommendations.map((rec) => `- ${rec.title}: ${rec.description}`),
    "",
    "Attention priorities:",
    ...attentionPriorities.map((note) => `- ${note.factor} (${note.priority}): ${note.reason}`),
    "",
    "Generated by Clinical Insight Engine",
  ].join("\n");
}
